### ISSUE TITLE
Merge pbs-ruby into ood_core

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#107]
This introduces the `ffi` dependency to ood_core and remove the pbs gem dependency.

Could under `job/adapters/torque/` directory which probably makes more sense and then do this:

| pbs-ruby  |  ood_core |
| ------------- | ------------- |
| `PBS`  | `OodCore::Job::Adapters::Torque`  |
| `PBS::Batch`  | `OodCore::Job::Adapters::Torque::Batch`  |
| `PBS::Torque`  | `OodCore::Job::Adapters::Torque::FFI`  |

* note that if you rename the `PBS::Torque` module to `FFI` then references to the main `FFI` class would need the `::` prefix i.e. `extend ::FFI::Library` and `class Attrl < ::FFI::Struct` and `::FFI::Pointer::NULL`. But that would probably be a better name since that module is the list of functions that provide the FFI interface. Also worth looking at other projects that use FFI for better naming inspiration. Other name could be `OodCore::Job::Adapters::Torque::CLib` or `OodCore::Job::Adapters::Torque::C` since it is the C library interface; the fact that we use FFI is an implementation detail (and arguably we could switch to Fiddle later anyways if there was a use case).

**Comment by MorganRodgers** [comment]
I like the idea of bringing the PBS adapter into `ood_core`. We are only going to use and support it in the context of OnDemand, so I agree that it doesn't make sense as a stand alone dependency.

**Comment by MorganRodgers** [comment]
Todo:

* [x] Initial git merge of projects
* [ ] Fix names
* [ ] Fix tests
