### ISSUE TITLE
Undefined method `split' for nil:NilClass: slurm

### ISSUE THREAD

**Issue by Pierrelemoine** [OSC/ood_core#119]
Hi,
I just installed Open-OnDemand with slurm 18.08 and CentOS 7.6.
It works great except for interactive desktop Active Jobs apps and Active jobs. I am however able to submit jobs with Jobs Composer without any error.

Active Jobs is not very verbose. It just says:
```cluster: undefined method `split' for nil:NilClass```

However Interactive apps is more verbose:
    Session was successfully created.
    Internal Server Error
    Please try again in a few moments. If you continue to see this error, please contact support.
    
    Details:
    #<NoMethodError: undefined method `split' for nil:NilClass>
    
    /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/ood_core-0.5.1/lib/ood_core/job/adapters/slurm.rb:429:in `duration_in_seconds'
    /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/ood_core-0.5.1/lib/ood_core/job/adapters/slurm.rb:484:in `parse_job_info'
    /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/ood_core-0.5.1/lib/ood_core/job/adapters/slurm.rb:334:in `block in info'
    /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/ood_core-0.5.1/lib/ood_core/job/adapters/slurm.rb:333:in `map'
    /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/ood_core-0.5.1/lib/ood_core/job/adapters/slurm.rb:333:in `info'
    /var/www/ood/apps/sys/dashboard/app/models/batch_connect/session.rb:270:in `update_info'...

After looking at the code, it seems related to the way Open-OnDemand parses the output of squeue.

Is that a known issue? Is there a way to fix that?

Thanks.

**Comment by treydock** [comment]
This is actually a bug in SLURM that affects OnDemand.  See https://github.com/OSC/ood-activejobs/issues/169.  We submitted a patch to SchedMD and also patched OnDemand: https://github.com/OSC/ood_core/commit/602e077e761ede2cc8bc241560918423330b3db5

Because the patch is to ood_core gem you would have to patch several apps.  It may be easier to just update to latest RPMs that have not yet been released publicly: https://yum.osc.edu/ondemand/latest/web/el7/x86_64/ondemand-1.4.9-1.el7.x86_64.rpm

**Comment by MorganRodgers** [comment]
@Pierrelemoine as @treydock mentioned we have a fix in the pipeline. If you prefer to continue with what you have at the moment we also have a patch script that will fix the issue: [patch_slurm18.sh](https://gist.github.com/MorganRodgers/c0c8e9b75352bcfa02aa120db104d3a1)

```
Usage:
  bash patch_slurm18.sh patch|unpatch
  patch: creates initializer files that remove the field 'gres' from the Slurm Adapter's native options
  unpatch: removes the initializer files, but leaves the directories intact
```
