### ISSUE TITLE
Make modifications to support Ruby 2.0.0

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#124]
Besides the use of ``<<~HEREDOC`` and "required" keyword args, see if there is any other code (or use of methods) that would prevent this code from running in Ruby 2.0.0.

The simple approach for this is to:

1. `bundle install --path vendor/bundle` on a system with Ruby 2.0.0
2. fix all of the tests that fail
3. have a discussion - is it worth it?

One of the benefits is we can use the library in other projects and run scripts on the login and compute nodes without a later Ruby.

**Comment by ericfranz** [comment]
We can discuss. One of the goals here would be the ability to use ood_core as a dependency in scripts that can work in the Ruby version that deploys by default with RHEL7.

**Comment by ericfranz** [comment]
We could also decide not to do this as well.

**Comment by MorganRodgers** [comment]
As discussed offline I am against this. This would be a non-trivial amount of development time to save a trivial amount of admin time.

If a system is going to have Ruby installed on it in the first place I do not see why it would be prohibitive to install a modern version of Ruby via Software Collections or another method.
