### ISSUE TITLE
If submit time is not available Slurm adapter crashes on squeue parsing

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#134]
submit_time is nil then this will crash https://github.com/OSC/ood_core/blob/29cfbb243fff817741159ecb35cd97b2b2e49ec7/lib/ood_core/job/adapters/slurm.rb#L494

this was experienced at a site where %k was producing multiple lines, introducing parsing issues

**Comment by ericfranz** [comment]
Easy way to test this is if we have a function to convert a slurm hash to an Info hash.

**Comment by MorganRodgers** [comment]
Fixed in #138, but without a separate test.
