### ISSUE TITLE
job_environment doesn't handle values with spaces

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#137]
The adapters turn the hashes into key value pairs in the command line arguments.

As a result I couldn't do something like this in the submit.yml.erb config in an interactive app:

```
script:
  job_environment:
    idea: This is a good idea
```

Instead I would need to do this:

```
script:
  job_environment:
    idea: "'This is a good idea'"
```

Then it would at least work in Torque.

**Comment by matthu017** [comment]
Can you give an example to help replicate the issue? Or point out the place where Script.new is initialized (ondemand maybe)?
This line shouldn't _need_ to use the `to_s` method. Whatever is calling it should have already parsed the yaml into a string. https://github.com/OSC/ood_core/blob/master/lib/ood_core/job/script.rb#L151
