### ISSUE TITLE
Adapters should favor `Array#concat` to `Array#+=` where appropriate

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#157]
The Slurm adapter is a good example. When using multiple lines to build a structure [like an array of job dependencies](https://github.com/OSC/ood_core/blob/d1de1a5651478c9564bcbfb03336be5f4eb6d72b/lib/ood_core/job/adapters/slurm.rb#L387-L392) we start with a literal construction and then use state changing methods such as `<<`.

However, in a method like `squeue_args` we do this: https://github.com/OSC/ood_core/blob/d1de1a5651478c9564bcbfb03336be5f4eb6d72b/lib/ood_core/job/adapters/slurm.rb#L149-L155

This is even more egregious in the submit method with the main args: https://github.com/OSC/ood_core/blob/d1de1a5651478c9564bcbfb03336be5f4eb6d72b/lib/ood_core/job/adapters/slurm.rb#L358-L384

Every `+=` creates a new array. Instead we should do something like this:

```ruby
args  = ["--all", "--states=all", "--noconvert"]
args.concat ["-o", "#{RECORD_SEPARATOR}#{options.join(UNIT_SEPARATOR)}"]
args.concat ["-u", owner.to_s] unless owner.to_s.empty?
args.concat ["-j", id.to_s] unless id.to_s.empty?
```

Of course, only where we start with a literal constructor.

**Comment by MorganRodgers** [comment]
This is a performance related concern?

**Comment by matthu017** [comment]
Pull Request: https://github.com/OSC/ood_core/pull/192
