### ISSUE TITLE
Support submission to specific nodes in the LinuxHostAdapter

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ood_core#164]
```
One other question. Is it possible to have more than one submit_host?
And/or to select what particular ssh_host to use?

The reason for this question is that we have 8 interactive only nodes, named 
frisco[1-8].chpc.utah.edu, that don’t face any cluster and which we use for
interactive work. Each of these machines has different hardware specs, so, users
commonly request a specific machine (e.g. frisco8 that has more CPUs/memory
if they need them).
```

This could be supported by adding a specific SSH target (`submit_host_override`?) in the `Script#native`. The target node would need to be in the `ssh_hosts` so that job status polling would continue to work. If no specific target node is specified we would default to the `submit_host`.

**Comment by ericfranz** [comment]
If we fix the interactive apps so you can have one app submit to multiple "clusters", would creating a separate "small" cluster config for each host (frisco[1-8].chpc.utah.edu) be preferable to using `Script#native`?

**Comment by MorganRodgers** [comment]
We should absolutely fix interactive apps so that a single app can submit to arbitrary clusters.

That said until we have a hardware config I'm not sure what multiple cluster configs gets us? I could see having a preference for keeping all of the nodes that the LinuxHost adapter targets in the same config.

**Comment by ericfranz** [comment]
Multiple cluster configs gets us not using native :-) which IMHO is a very unfavorable way to provide adapter specific functionality.
