### ISSUE TITLE
Duplication between Info#procs and Info#allocated_nodes?

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#17]
```
      # Set of machines that is utilized for job execution
      # @return [Array<NodeInfo>] allocated nodes
      attr_reader :allocated_nodes
```

and

```
      # Number of procs allocated for job
      # @return [Fixnum, nil] allocated total number of procs
      attr_reader :procs
```

In what case will this be true:

```ruby
info.allocated_nodes(&:procs).reduce(&:procs) != info.procs
```

**Comment by brianmcmichael** [comment]
That will be true before the job has run and `:allocated_nodes` == 0, but requested nodes > 1.

See: 

https://github.com/OSC/ood-activejobs/blob/ood_core/doc/slurm_queued.png

**Comment by ericfranz** [comment]
Okay, so then `allocated_nodes` is the number of allocated nodes, with procs on each node specified. Whereas `procs` is really `total number of procs requested` instead of `total number of procs allocated`?

In other words, is the comment above `procs` incorrect, as it is `procs requested` instead of `procs allocated`?

**Comment by ericfranz** [comment]
Or perhaps this is dependent on the resource manager and adapter being used. For example, it might be useful to see the total number of procs allocated once a job has started, even if those procs are spread over 8 different nodes.

**Comment by nickjer** [comment]
Two things:

- if the job is queued, then `#procs` is resource manager dependent on whether it is # procs allocated or 0
- if the job is running, then this...

  ```ruby
  info.allocated_nodes(&:procs).reduce(&:procs) != info.procs
  ```

  is also resource manager dependent. For the case of Slurm we know the list of nodes allocated for the job, but we don't necessarily know the `NodeInfo#procs`. So the above is equivalent to for 100 allocated procs...

  ```ruby
  0 != 100
  ```
