### ISSUE TITLE
Make the "ssh wrapper" pattern a first class citizen

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#170]
Like with the linux host adapter, in the job config if you specify `submit_host: "some_other_host"` then when executing the command to submit the batch job, each adapter would execute that command, its arguments, etc. on another host via ssh. This is the main scope of this feature.

A second feature would be to add another config `use_submit_host_for_all_commands: true` (a better name?), every adapter that doesn't use the C API should execute all of the scheduler commands on the specified submit host (qstat, qdel, qhold, etc.). This is problematic, however, for adapters that use the C API via FFI for anything (SGE, Torque).

Currently, the only way to use this "ssh wrapper" pattern is for a site to provide their own ssh wrapper scripts and use bin_overrides. This is onerous enough that it is not used by default, and we don't even document well how to do it.

**Comment by ericfranz** [comment]
This would not work for sge or the torque adapters since they both make use of the C libraries. But this would work for Slurm and LSF.

**Comment by MorganRodgers** [comment]
This should be doable in PBSPro as well, it would also work for SGE if the site can accept less nuanced job states by not using DRMAA.

**Comment by ericfranz** [comment]
We could support two options: ssh for just job submission, and ssh for all commands
