### ISSUE TITLE
Add qos to Script and support option in Torque and Slurm

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#195]
See https://slurm.schedmd.com/rosetta.pdf for Quality of Service

For more info on qos in Slurm see https://slurm.schedmd.com/qos.html

See an example implementation here, which is really straightforward and simple:

https://discourse.osc.edu/t/changes-to-file-structure-after-update-to-1-7/874/3?u=efranz

**Comment by treydock** [comment]
FWIW setting QOS could be something required for OSC when we migrate to SLURM, but details still being worked out if we will make people ask for a QOS or if we will pick one for them based on who they are and which partition they request.  The automagic picking would be done in submit filter so be invisible to OnDemand.
