### ISSUE TITLE
SGE provide native attributes

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood_core#197]
While implementing [extended view in the active jobs](https://github.com/OSC/ondemand/issues/399) for SGE, it was found there's a little to be desired in the way it provides `native` data.

Indeed, there are these TODOs
https://github.com/OSC/ood_core/blob/63187f8874e62b752a73e39263f539ce0241495a/lib/ood_core/job/adapters/sge/qstat_xml_j_r_listener.rb#L31
and here
https://github.com/OSC/ood_core/blob/63187f8874e62b752a73e39263f539ce0241495a/lib/ood_core/job/adapters/sge/qstat_xml_r_listener.rb#L27

So this ticket is to do that. provide whatever data is available in the `native` attribute.

**Comment by ericfranz** [comment]
This can be used to test what you get back (of course consult documentation as well) https://github.com/OSC/ood-images/tree/master/vagrant-with-gridengine

**Comment by matthu017** [comment]
Need to add more information to the README in that folder & small changes. Will submit a pr request later for ood-images.
