### ISSUE TITLE
UGE showing wrong wallclock and/or dispatch time?

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood_core#199]
This [discourse topic about UGE showing the wrong time remaining](https://discourse.osc.edu/t/time-remaining-incorrect/970) in a batch connect application came in today.  It's assumed this is a bug in the adapter and not the dashboard.

Here's the [output of uge's 'qstat -r -xml'](https://github.com/OSC/ood_core/files/4759395/qstat_uge.xml.txt) to help replicate the issue. I'd say we need a test case to replicate the issue as I cannot by hacking around in irb.  [Here's the relevant dashboard code that displays the time remaining time](https://github.com/OSC/ondemand/blob/adf2f5a91846b21213406641eb303e3bad641d79/apps/dashboard/app/helpers/batch_connect/sessions_helper.rb#L59-L82).

It should be noted that `Time.now` is taken into account for these calculations so that should be stubbed to appropriately reflect a time > dispatch time but < 4 hours past the dispatch time.

**Comment by matthu017** [comment]
It depends on which method the code is calling in batch.rb
https://github.com/OSC/ood_core/blob/master/lib/ood_core/job/adapters/sge/batch.rb#L59-L116
If it is calling qstat_xml_j_r_listener, wallclock_time simply doesn't exist which may have caused the problem.

**Comment by matthu017** [comment]
We might want to combine this with issue https://github.com/OSC/ood_core/issues/197

**Comment by johrstrom** [comment]
You're right that it's the JR listener, and `'qstat', '-r', '-xml', '-j', job_id.to_s` seem to be the command.

But looking at [the example output](https://github.com/OSC/ood_core/blob/63187f8874e62b752a73e39263f539ce0241495a/spec/job/adapters/sge/output_examples/qstat_jr.xml) it's the under `h_rt`. we just need to extract it?

This can't go into native attributes, because things like the dashboard access the wall_time directly. They shouldn't have to toggle to do something strange for separate adapters.  Native is for things that can't go everywhere, or it's a catch all for things that don't fit. wall time is one of those things all schedulers use (classic schedulers anyhow).

**Comment by matthu017** [comment]
My bad, it is qstat_xml_r that where `wallclock_time` doesn't exist. 
After looking at JR listener, it should work as intended.

**Comment by johrstrom** [comment]
No issues, that's what the 'needs investigation' tag means, it's not clear why it's going on.  i

And looking at [the spec file, this is supposed to work](https://github.com/OSC/ood_core/blob/63187f8874e62b752a73e39263f539ce0241495a/spec/job/adapters/sge/batch_spec.rb#L142-L151) so there could be something amiss either in the way we parse, or the test case or UGE is somehow different from SGE.  I'm sure the discourse user would be happy to provide new output to test against.  Maybe the first step would be just to copy this test case and run it against the UGE output.

Btw, you can get [a trial version of UGE to test against here](https://www.univa.com/resources/univa-grid-engine-trial.php).

**Comment by johrstrom** [comment]
OK I got it. UGE's `JAT_start_time` is returning milliseconds past the epoch (13 digits) where SGE and (our tests) look at seconds past the epoch (10 digits).  

`wallclock_time` is being set to some very large negative value here. 
https://github.com/OSC/ood_core/blob/9eaf3cfe937657104f7d16b4bf2452be18cbdebc/lib/ood_core/job/adapters/sge/qstat_xml_j_r_listener.rb#L128-L132

To get the remaining time, we subtract this from the time limit, say an hour (3600), resulting in a very large positive number.

```irb
irb(main):041:0> wallclock = Time.now.to_i - 1592928425042
=> -1591335487093
irb(main):042:0> distance_of_time_in_words(3600 - wallclock, 0, false, :only => [:minutes, :hours], :accumulate_on => :hours)
=> "442037636 hours and 18 minutes"
```

**Comment by ericfranz** [comment]
I guess we could use a UGE image :-)

**Comment by ericfranz** [comment]
But with that description we can write a test.
