### ISSUE TITLE
Add an Job::Adapter#info_where as alternative to info_all

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#26]
An example: `Adapter#info_where(user: "efranz")` or maybe better is `Adapter#info_where_user("efranz")`. We could also add `Adapter#info_where_queue("debug")` etc.

The `Adapter` superclass can offer a default implementation, which does a select on the results from `info_all`.

Individual adapters can optionally override with an optimized implementation. For example, bjobs by default shows only the user's jobs.

It could also be a `Adapter#info_where` filter and accept a hash where keys are methods on `Job::Info`.

**Comment by nickjer** [comment]
I think we should first run benchmarks across the various resource managers for each of these filters to determine whether it would be beneficial to implement this feature or continue to use `Enumerable#select` and `Enumerable#reject` instead.

**Comment by nickjer** [comment]
Not sure about introducing a new function. Maybe just extending `#info_all` with:

```ruby
adapter.info_all(user: "efranz")
```

**Comment by nickjer** [comment]
But I can see that `Adapter#info_where_user("efranz")` is attractive, since new adapters don't have to handle it if they don't want to,

**Comment by ericfranz** [comment]
Also a new method means we don't introduce control coupling
