### ISSUE TITLE
Environment variables are not passed to mpirun or srun within an interactive desktop

### ISSUE THREAD

**Issue by lebonez** [OSC/ood_core#270]
Have a strange issue where if I run srun or mpirun in a interactive desktop it doesn't seem to get environment variables. If I check env it has everything set correctly from the terminal inside the interactive desktop so I'm unsure where the disconnect is. All of these work correctly if I'm just running from a login node using salloc -N 2 --ntasks-per-node 4 beforehand. 

srun hostname
test@node1:~$ srun date
slurmstepd: error: execve(): date: No such file or directory
slurmstepd: error: execve(): date: No such file or directory
slurmstepd: error: execve(): date: No such file or directory
slurmstepd: error: execve(): date: No such file or directory
slurmstepd: error: execve(): date: No such file or directory
slurmstepd: error: execve(): date: No such file or directory
slurmstepd: error: execve(): date: No such file or directory
slurmstepd: error: execve(): date: No such file or directory
srun: error: node1: tasks 0-3: Exited with exit code 2
srun: error: node2: tasks 4-7: Exited with exit code 2

test@node1:~$ mpirun --mca plm_base_verbose 100 -x PATH hostname
[node1.example.com:3954939] mca: base: components_register: registering framework plm components
[node1.example.com:3954939] mca: base: components_register: found loaded component slurm
[node1.example.com:3954939] mca: base: components_register: component slurm register function successful
[node1.example.com:3954939] mca: base: components_register: found loaded component rsh
[node1.example.com:3954939] mca: base: components_register: component rsh register function successful
[node1.example.com:3954939] mca: base: components_register: found loaded component isolated
[node1.example.com:3954939] mca: base: components_register: component isolated has no register or open function
[node1.example.com:3954939] mca: base: components_open: opening plm components
[node1.example.com:3954939] mca: base: components_open: found loaded component slurm
[node1.example.com:3954939] mca: base: components_open: component slurm open function successful
[node1.example.com:3954939] mca: base: components_open: found loaded component rsh
[node1.example.com:3954939] mca: base: components_open: component rsh open function successful
[node1.example.com:3954939] mca: base: components_open: found loaded component isolated
[node1.example.com:3954939] mca: base: components_open: component isolated open function successful
[node1.example.com:3954939] mca:base:select: Auto-selecting plm components
[node1.example.com:3954939] mca:base:select:(  plm) Querying component [slurm]
[node1.example.com:3954939] mca:base:select:(  plm) Query of component [slurm] set priority to 75
[node1.example.com:3954939] mca:base:select:(  plm) Querying component [rsh]
[node1.example.com:3954939] mca:base:select:(  plm) Query of component [rsh] set priority to 10
[node1.example.com:3954939] mca:base:select:(  plm) Querying component [isolated]
[node1.example.com:3954939] mca:base:select:(  plm) Query of component [isolated] set priority to 0
[node1.example.com:3954939] mca:base:select:(  plm) Selected component [slurm]
[node1.example.com:3954939] mca: base: close: component rsh closed
[node1.example.com:3954939] mca: base: close: unloading component rsh
[node1.example.com:3954939] mca: base: close: component isolated closed
[node1.example.com:3954939] mca: base: close: unloading component isolated
[node1.example.com:3954939] [[3208,0],0] plm:slurm: final top-level argv:
	srun --ntasks-per-node=1 --kill-on-bad-exit --nodes=1 --nodelist=node2 --ntasks=1 orted -mca ess "slurm" -mca ess_base_jobid "210239488" -mca ess_base_vpid "1" -mca ess_base_num_procs "2" -mca orte_node_regex "node[2:2-3]@0(2)" -mca orte_hnp_uri "210239488.0;tcp://10.10.44.12:51155" --mca plm_base_verbose "100"
srun: error: node2: task 0: Exited with exit code 2
srun: launch/slurm: _step_signal: Terminating StepId=1383.41
slurmstepd: error: execve(): orted: No such file or directory
--------------------------------------------------------------------------
An ORTE daemon has unexpectedly failed after launch and before
communicating back to mpirun. This could be caused by a number
of factors, including an inability to create a connection back
to mpirun due to a lack of common network interfaces and/or no
route found between them. Please check network connectivity
(including firewalls and network routing requirements).
--------------------------------------------------------------------------
[node1.example.com:3954939] mca: base: close: component slurm closed
[node1.example.com:3954939] mca: base: close: unloading component slurm

Now it works if I do this:
test@node:~$ srun --export=ALL date
Sat 01 May 2021 07:15:48 AM CDT
Sat 01 May 2021 07:15:48 AM CDT
Sat 01 May 2021 07:15:48 AM CDT
Sat 01 May 2021 07:15:48 AM CDT
Sat 01 May 2021 07:15:48 AM CDT
Sat 01 May 2021 07:15:48 AM CDT
Sat 01 May 2021 07:15:48 AM CDT
Sat 01 May 2021 07:15:48 AM CDT

**Comment by lebonez** [comment]
If I run srun with the full path /usr/bin/echo it works
test@node1:~$ srun echo $PATH
slurmstepd: error: execve(): echo: No such file or directory
slurmstepd: error: execve(): echo: No such file or directory
slurmstepd: error: execve(): echo: No such file or directory
slurmstepd: error: execve(): echo: No such file or directory
srun: error: node1: tasks 0-3: Exited with exit code 2

test@node1:~$ srun /usr/bin/echo $PATH
/opt/TurboVNC/bin/:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/test/go/bin
/opt/TurboVNC/bin/:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/test/go/bin
/opt/TurboVNC/bin/:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/test/go/bin
/opt/TurboVNC/bin/:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/test/go/bin


If I add --export=PATH to the native script in my_submit.yml.erb the srun works but it doesn't set any of the paths that are typically included like /usr/local/bin. Here is the path returned by srun.
test@node1:~$ srun echo $PATH
/opt/TurboVNC/bin/:/opt/ood/ondemand/root/usr/share/gems/2.5/bin:/opt/ood/ondemand/root/usr/bin:/opt/ood/ondemand/root/usr/sbin:/sbin:/bin:/usr/sbin:/usr/bin

**Comment by lebonez** [comment]
In summary, it seems if I run the interactive desktop on a single node as an example 'srun hostname' fails and 'mpirun hostname' works.
With multiple nodes both 'srun hostname' and 'mpirun hostname' fail.
If I specify full path such as 'srun /usr/bin/hostname' it always works multi or single node.
The part that really matters is 'mpirun /usr/bin/hostname' and 'mpirun hostname' fails always because it is trying to find all kinds of stuff in the initial execution and can't because it's path seems messed up.

**Comment by johrstrom** [comment]
We default to `--export=NONE` when we schedule the Slurm jobs. 

We fixed this at OSC by setting the environment variable in the job. So the job is submitted initially with `NONE`, but then switches to `ALL` so stuff like `srun` works.
https://github.com/OSC/osc-ood-config/blob/13f0c677b3b53a7d94ff1b9dfdb0b4886eebd45f/ondemand.osc.edu/apps/bc_desktop/submit/slurm.yml.erb#L69-L70

**Comment by lebonez** [comment]
this fixed it thanks! Didn't know you could modify the before script like so.
