### ISSUE TITLE
Stack traced produced by K8 adapter

### ISSUE THREAD

**Issue by treydock** [OSC/ood_core#278]
<img width="1363" alt="Screen Shot 2021-05-17 at 11 07 56 AM" src="https://user-images.githubusercontent.com/739622/118511692-27c46f00-b700-11eb-94fd-706d4d9db2f5.png">

If I run the pod YAML manually things seem to work just fine.

**Comment by treydock** [comment]
I found issue. This was a GPU pod, so I was setting number of GPUs and the environment I was using didn't support GPU pods, since only OSC test environment at this time has GPU nodes.  The dev environment where I got this error does not have GPU worker nodes.  So likely solution maybe just more graceful handling of this error.

**Comment by johrstrom** [comment]
Yea because it's your dev dashboard, you see the error. I think the system dashboard would have caught it?

Even so, it doesn't seem that debuggable so there's definitely room for improvement here.

**Comment by treydock** [comment]
I ended up having to modify code to print the backtrace from ood_core cause the backtrace inside OnDemand was for the dashboard itself and didn't show where in ood_core the issue lied.

**Comment by treydock** [comment]
I didn't commit my changes to #279 , I merely fixed the failing condition
