### ISSUE TITLE
Kubernetes contexts collide if used outside OnDemand

### ISSUE THREAD

**Issue by treydock** [OSC/ood_core#283]
Using ondemand-test I began to have initialization issues like this:

```
$ kubectl get services jupyter-2iee6rcf-service -n user-tdockendorf
Error from server (NotFound): services "jupyter-2iee6rcf-service" not found
```
This is from within a running pod.  The issue is context used is the context I setup outside OnDemand for interacting with Kubernetes dev:

```
$ kubectl config current-context
tdockendorf@kubernetes-dev
```

Ideally any kubectl commands executed from within the containers to do initialization would also be using same context flags as OnDemand so that there is not the assumption that the default context is correct.

**Comment by treydock** [comment]
Ugly solution is to set `KUBECONFIG` inside the pod to `/dev/null`. I think my `$HOME/.kube/config` was conflicting with the pod environment too much , like especially the fact that the Kubernetes CA cert we use might not exist inside the pod since we reference a path not in `$HOME`.

```
[tdockendorf@jupyter-2iee6rcf /]$ kubectl config set-context ood-test
Context "ood-test" modified.
[tdockendorf@jupyter-2iee6rcf /]$ kubectl get services jupyter-2iee6rcf-service -n user-tdockendorf
Error from server (NotFound): services "jupyter-2iee6rcf-service" not found
```

The fix:

```
[tdockendorf@jupyter-2iee6rcf /]$ export KUBECONFIG=/dev/null
[tdockendorf@jupyter-2iee6rcf /]$ kubectl get services jupyter-2iee6rcf-service -n user-tdockendorf
NAME                       TYPE       CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE
jupyter-2iee6rcf-service   NodePort   10.96.0.85   <none>        80:30101/TCP   10m
```

**Comment by treydock** [comment]
To further illustrate the issue with using out of $HOME Kubernetes CA from within a pod:

```
[tdockendorf@jupyter-wabp9hur /]$ kubectl get services jupyter-wabp9hur-service --context ood-test
error: unable to read certificate-authority /opt/osc/etc/kubernetes-ca.crt for ood-test due to open /opt/osc/etc/kubernetes-ca.crt: no such file or directory
```
One thing that's handy is if you copy the CA to `$HOME/.kube` and then load it in with `kubectl config set-cluster`, the path in KUBECONFIG becomes relative to the `$HOME/.kube` directory:

```
clusters:
- cluster:
    certificate-authority: kubecontroller-dev-ca.crt
    server: https://kubecontroller-dev.OMIT:6443
  name: kubernetes-dev
```

The above is from these steps:

```
cp /systems/osc_certs/kubecontroller-dev-ca.crt ~/.kube/
kubectl config set-cluster kubernetes-dev --server=https://kubecontroller-dev.OMIT:6443 --certificate-authority=$HOME/.kube/kubecontroller-dev-ca.crt
```

**Comment by treydock** [comment]
@johrstrom So far I've worked around this problem by setting `KUBECONFIG` environment variable to `/dev/null` for apps I have worked on.  Because the RBAC for OnDemand expects kubectl within the pod to use `default` ServiceAccount, I wonder if we should make the `KUBECONFIG` change something part of the template or if it's more of a documentation type thing?

**Comment by johrstrom** [comment]
I think if we had it as a part of the template is the way to go. 

The way we have environment merging setup, if we force it to be `/dev/null` then someone can simply override it right? That way the default works for 80% of folks and others have a way to set it to what they want.
