### ISSUE TITLE
publish to ruby gems on tags

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood_core#285]
We manually create tags and build the gem then publish to rubygems. This ticket is to build automation around publishing to rubygems through a service account when tags are created.

**Comment by ericfranz** [comment]
Now that we have a monorepo, with all the Rails apps merged except for the Job Composer, we should merge this repo into the dashboard first. A straightforward way to do that would be to:

1. add a gems directory under the dashboard app and place this there (i.e. apps/dashboard/gems/ood_core)
2. update Gemfile in dashboard to use path: "gems/ood_core"
3. update Gemfile in job composer to use path "../dashboard/gems/ood_core" (maybe need to resolve to real path - so resolve symlinks, so this would work even when cloned into dev dashboard and when you are playing games with symlinks)

While the solution is not ideal for the job composer, it is ideal for the dashboard app.

One challenge if you do this is - how do you tag new rubygem builds? Some projects that have gems in monorepos just have the ruby gem build match the repo tag version. You lose semantic versioning on the ruby gem, but then it is easier to follow.

I think the benefits of merging the gems with this approach outweigh the drawbacks - changes that involve ood_core and the dashboard become 1 change, testing on branches is easier, experiments locally is easier, refactoring common code from the apps into ood_core is easier, etc.
