### ISSUE TITLE
LHA crashes when it can't parse ssh output correctly

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood_core#297]
We got an INC recently where a user was encountering this issue.  It turns out it was an issue in their ~/.bashrc file that was the cause. 

I was unable to replicate with at statement like this`./apps/python/3.6-conda5.2/etc/profile.d/conda.sh` (which errors saying no such file or directory).  I believe the user had a similar statement, trying to source a conda environment file, but again I cannot replicate with that alone so there's something else I'm missing.

```text
#<NoMethodError: undefined method `start_with?' for nil:NilClass>
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host/launcher.rb:259:in `block in list_remote_tmux_session'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host/launcher.rb:258:in `select'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host/launcher.rb:258:in `list_remote_tmux_session'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host/launcher.rb:90:in `block in list_remote_sessions'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host/launcher.rb:89:in `map'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host/launcher.rb:89:in `list_remote_sessions'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host.rb:95:in `info_all'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.10/gems/ood_core-0.17.1/lib/ood_core/job/adapters/linux_host.rb:151:in `info' 
```

**Comment by treydock** [comment]
@johrstrom For a fix, would it be sufficient to guard against calling a function on nil or would we need to figure out a way to reproduce the error and handle the parsing to avoid it?

**Comment by johrstrom** [comment]
Yea we should replicate.  I suspect it's something to do with #258 and the upgrades we needed for tmux 2. 

Because we end up using the same thing to split.
https://github.com/OSC/ood_core/blob/d196e9dc44ea5f4a3b08a8cd80ca71e0a1594623/lib/ood_core/job/adapters/linux_host/launcher.rb#L254

tmux 2 didn't like the unicode separator, but clearly real characters may give some issues.

I pulled the card and this is what the `jobid@host` got parsed as.  
![image](https://user-images.githubusercontent.com/4874123/124171363-780c4c00-da76-11eb-9ec3-8b1daeb21a0b.png)

So yea, we clearly need a much more rock solid way to deal with whatever ssh output throws at us.

**Comment by treydock** [comment]
@johrstrom If you want a way to replicate that, I think I know where that output is coming from, it's `OSCusage` and as an OSC staff member you should be able to pull down the output they are seeing.

**Comment by johrstrom** [comment]
I was able to replicate by adding `OSCusage` command to my ~/.bashrc.  For whatever reason it can't handle the extra output.
