### ISSUE TITLE
Add walltime requested to `Job::Info`

### ISSUE THREAD

**Issue by nickjer** [OSC/ood_core#34]
I think we should add the total requested wall time to the `OodCore::Job::Info` object. It could be called `wallclock_requested` or `wallcock_total`.

**Comment by nickjer** [comment]
One of the issues encountered is that I can submit a job without specifying the wall time and it uses the system default. And I am unable to get back this information

**Comment by ericfranz** [comment]
I won't have this for LSF.

**Comment by nickjer** [comment]
Does LSF not support it? Or you just won't have time to get around to implementing it?

**Comment by ericfranz** [comment]
Short answer is no.

With LSF 8.3 there is no way to control the output formatting of individual values like we do in the Slurm adapter. LSF 9+ seems to have some options for the bjobs and for that I may be able to get the RUNLIMIT. So for current adapter this will be nil.

Long answer:

Using long format `bjobs -l` appears to display a RUNLIMIT value for some of the running jobs (unfortunately, not all the jobs in the running state display this). However, that format is difficult to parse and not worth the time.

Instead we use `bjobs -u all -a -w -W`, and `-w` for wide format is key, which avoids truncating column values. When I use this with `-W` I get these columns:

    JOBID USER STAT QUEUE FROM_HOST EXEC_HOST JOB_NAME SUBMIT_TIME PROJ_NAME CPU_USED MEM SWAP PIDS START_TIME FINISH_TIME

But finish time is `-` unless the job is completed. There are no resource limits displayed.

**Comment by nickjer** [comment]
Alright, will keep this in mind for the batch connect work.
