### ISSUE TITLE
Hostname doesn't give correct host all the time

### ISSUE THREAD

**Issue by nickjer** [OSC/ood_core#42]
This line:

https://github.com/OSC/ood_core/blob/2086895d8d829c03c683e7af3902b52d4f26fb4a/lib/ood_core/batch_connect/template.rb#L129

uses `hostname` to get the host of the machine.

At Arizona, this gives:

```sh
┌─[jnicklas@i1n5][~]
└─▪ hostname
i1n5
```

which we are unable to SSH to from the OnDemand node. Maybe this can be fixed by the sys admins, but an alternative solution may need to be looked into. For example:

```sh
┌─[jnicklas@i1n5][~]
└─▪ hostname -A
i1n5.ocelote.hpc.arizona.edu i1n5.cm.cluster i1n5.ib.cluster 
```

where I am able to successfully SSH to `i1n5.ocelote.hpc.arizona.edu` from the OnDemand node.

**Comment by ericfranz** [comment]
Discussed offline. We will do this:

```diff
+# bash script content to set the "host" env var to the host that
+# the server we are connecting to is running on
+def set_hostname
+  context.fetch(:set_hostname, "host=$(hostname)")
+end

# Source in a developer defined script before running the main script
def before_script
  context.fetch(:before_script) do
    before_file = context.fetch(:before_file, "before.sh").to_s

-   "host=$(hostname)\n[[ -e \"#{before_file}\" ]] && source \"#{before_file}\""
+   "[[ -e \"#{before_file}\" ]] && source \"#{before_file}\""
  end.to_s
end

# ...

# The base script template
def base_script
  # ...

+ #{set_hostname}
  #{before_script}
```

* Setting the host (which is used in the connection parameters) is a separate concern from creating an optional before_script to do other setup. So we separate this into separate steps.
* In cluster config I can override this with custom script string to set the host parameter
