### ISSUE TITLE
Should we keep maintaining separate gems for resource manager adapters?

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#44]
This issue is to capture a discussion around the merits of continuing to maintains separate gems for resource manager adapters, now that we have ood_core.

Original suggestion from @nickjer on the LSF performance issues sparked this discussion:

@nickjer:

>I feel if you go this route, it may be best to break this off into a separate gem much like pbs-ruby.

@ericfranz:

>I don't think we will realize any benefits by breaking this off into a separate gem.

**Comment by brianmcmichael** [comment]
> PBS-Ruby is the one Gem that's been relatively stable around here and it's been used in all of our App Kit instances. Taking the time to prepare a separate LSF Gem would reduce the overhead of having to recreate the LSF code in any future iteration. Additionally, it would give sites the ability to use the adapter directly in their apps.

> I'd say that a tangental benefit would be that it would give OSC the authority that goes with having created these open-source adapters, but since we're not an LSF site I guess our ability to adequately maintain the gems is questionable.

Originally posted at [#40](https://github.com/OSC/ood_core/issues/40#issuecomment-311678578)

**Comment by ericfranz** [comment]
@nickjer writes:

There are a few benefits to a full LSF library being in a separate gem.

- Improvements can be added to it without directly affecting the overall `ood_core` gem. So a patch to the LSF gem won't affect every OOD installation. We would only need to tell the LSF sites to update the LSF gem.

- You can also add support for other LSF features such as getting the status of a server, queue, or node that isn't directly related to what `ood_core`'s current capabilities are, similar to what pbs-ruby currently provides.

- If the LSF gem does require dependencies in the future outside of the standard library it won't affect the dependencies required by `ood_core`. And centers that don't use LSF won't need to install those dependencies.

**Comment by ericfranz** [comment]
@ericfranz writes:

We can add LSF specific features to the batch object and just document it. The other two benefits won't be realized by our project. And in fact, if there ever would be a time where it would be really beneficial to separate out two gems, that's the time to do it.

**Comment by ericfranz** [comment]
Not doing. See https://github.com/OSC/ood_core/issues/107
