### ISSUE TITLE
TurboVNC 2.2.90 lacks the -nohttpd option

### ISSUE THREAD

**Issue by ECoulter** [OSC/ood_core#737]
Using the TurboVNC repo and pulling the 'turbovnc' package results in a version of TurboVNC on Rocky 8 (and I assume other RHEL 8 variants) which fails when called with -nohttpd, breaking the default bc_desktop app, thanks to its inclusion in vnc.rb - http server support has been dropped for newer versions of TurboVNC, though it will be supported in 2.2.x versions. (See release notes here: https://github.com/TurboVNC/turbovnc/releases/tag/3.0beta1) 

Not sure what the most sustainable fix is, perhaps just mentioning this in the documentation at https://osc.github.io/ood-documentation/latest/app-development/interactive/setup/enable-reverse-proxy.html... This is really just a heads up - possible to continue with new installs using an older TurboVNC version just fine.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201625178070145/1201627216789264) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
what? I closed the ondemand duplicate and it closed this one too?

In any case - yea seems like in the shell script we can check what version it is and have a toggle for the same.

**Comment by sjpb** [comment]
Just hit this on Rocky 8.5 with  TurboVNC Server (Xvnc) 64-bit v2.2.90 (build 20211222).
