### ISSUE TITLE
Getting list of batch server queues/partitions 

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood_core#77]
Community request:

Support getting a list of batch server queues/partitions

**Comment by nickjer** [comment]
This is the same as https://github.com/OSC/ood_core/issues/1

**Comment by johrstrom** [comment]
This is a duplicate of #1 so I'm closing.  This says community request, but there's no link to get further context. In any case, it looks like it's being discussed in the other ticket anyhow.
