### ISSUE TITLE
DdddWith simplicity comes limitations, like with most things.  RSpec makes it easy to do complex stubbing (mocking) as well as support numerous kinds of matchers that read well.  Also keeping tests from spilling into other tests is a huge benefit to RSpec.

### ISSUE THREAD

**Issue by 253700ratchakon** [OSC/ood_core#855]
With simplicity comes limitations, like with most things.  RSpec makes it easy to do complex stubbing (mocking) as well as support numerous kinds of matchers that read well.  Also keeping tests from spilling into other tests is a huge benefit to RSpec.

Before you fully commit to replacing RSpec, might be good to take one of two complex test cases from each RSpec file and make sure you can adequately replace them with minitest.  Simplicity at the cost of functionality is not a good trade off.  If minitest is going to make testing less reliable or function in a way that makes them less useful, that seems like a deal breaker.

Also the e2e tests in main OnDemand repo have to stay with Rspec cause there is simply no way to use minitest to replace beaker-rspec plugin.

_Originally posted by @treydock in https://github.com/OSC/ood_core/issues/844#issuecomment-2221715113_

**Comment by johrstrom** [comment]
Not sure why you opened this, if it was an accident or what, but we are indeed moving to minitest instead of rspec.
