### ISSUE TITLE
Check for cluster configs that have "yaml" extension

### ISSUE THREAD

**Issue by nickjer** [OSC/ood_core#87]
Currently we only detect cluster configuration files that have the extension `*.yml`, but `*.yaml` is a valid YAML extension that should also be checked.

This has led to confusion in issue https://github.com/OSC/ood-activejobs/issues/157

Relevant code is:

https://github.com/OSC/ood_core/blob/db08d7ab790b542b0b033325c25467f80fcb8ead/lib/ood_core/clusters.rb#L12-L44

**Comment by ericfranz** [comment]
Along with this, enumerate all the other places in OnDemand where we load yaml files. We should support both extensions everywhere.

**Comment by ericfranz** [comment]
A simple solution would be to change `Pathname.glob(config.join("*.yml")).each do |p|` to `Pathname.glob(config.join("*.y*ml")).each do |p|`

```
irb(main):006:0> Pathname.glob(Pathname.new('tmp').join('*.yml'))
=> [#<Pathname:tmp/bar.yml>]
irb(main):007:0> Pathname.glob(Pathname.new('tmp').join('*.yaml'))
=> [#<Pathname:tmp/bar.yaml>]
irb(main):008:0> Pathname.glob(Pathname.new('tmp').join('*.y*ml'))
=> [#<Pathname:tmp/bar.yml>, #<Pathname:tmp/bar.yaml>]
```

**Comment by matthu017** [comment]
https://github.com/OSC/ood_core/commit/1dbe5a72101d142dffe21678c99e2e16ca1a67a1
