### ISSUE TITLE
Method of generating password causes problems if compute node locale is not UTF8

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#91]
See https://listsprd.osu.edu/pipermail/ood-users/2018-August/000206.html

Perhaps we should use a different approach that would reliably work, even when the locale on the compute nodes is en_US instead of en_US.UTF-8

**Comment by ericfranz** [comment]
The code:

https://github.com/OSC/ood_core/blob/d21a1d62a41b1a3e6d05a28cfe1100bb931597f9/lib/ood_core/batch_connect/template.rb#L145-L148 

Alternatives? Perhaps instead of `tr -cd '[:alnum:]'` we should be more explicit and do `tr -cd 'A-Z-a-z-0-9'`.

**Comment by ericfranz** [comment]
An easy way to test would be to find offending characters, put it in a file and then do:

```
tr -cd '[:alnum:]' < /path/to/big/file/with/offending/characters 2> /dev/null | head -c${1:-#{passwd_size}} 
```

Then we can experiment/test/verify the difference. Or the create_passwd function accepts an optional argument and the file used in the function is either /dev/urandom or the file specified by the argument.

**Comment by ke3vin** [comment]
You can also experiment  just by setting LANG (or LC_CTYPE) prior to running your test.
It appears that with LANG set to en_US, the `[:alnum:]` argument to `tr` generates a bunch of characters with their high bit set, I'm not sure why.  If LANG is set to en_US.UTF_8, it works correctly.
Using `tr -cd 'A-Za-z0-9'` works correctly in both cases.

**Comment by ericfranz** [comment]
#94 uses `tr -cd 'A-Za-z0-9'` to fix the problem. Thank you @ke3vin for the help!
