### ISSUE TITLE
Slurm Adapter partially incompatible with Slurm 18

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#99]
We should test with Slurm 18 and see what potential issues exists. We heard reports that the Active Jobs app did not work with Slurm 18 but job submission did work.

**Comment by MorganRodgers** [comment]
Using [a modified ood-images-full](https://github.com/OSC/ood-images-full/tree/slurm18) I can confirm that job submission works. ActiveJobs fails if there are any active jobs...with the error:

```
Example Cluster: undefined method `split' for nil:NilClass
```

I'm looking into what is going on.

**Comment by MorganRodgers** [comment]
It appears that the `squeue` format code `%b` has been removed which shifts the delimited text which causes things to be parsed incorrectly.

**Comment by MorganRodgers** [comment]
Fix in c18fe4511bf3

**Comment by MorganRodgers** [comment]
Closing because #110 is a much simpler fix.
